trigger:
  branches:
    include:
      - release/*
      
jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    displayName: Build and Deploy
    steps:
    - checkout: self

    - task: Docker@0
      displayName: 'Build image'
      inputs:
        azureSubscription: 'NR PMP DEVQA (21191caf-8a0a-4a0f-b34d-afae216ee5b3)'
        azureContainerRegistry: '{"loginServer":"acrmcataniatestwesteu.azurecr.io", "id" : "/subscriptions/21191caf-8a0a-4a0f-b34d-afae216ee5b3/resourceGroups/rg-mcatania-test-westeu/providers/Microsoft.ContainerRegistry/registries/acrmcataniatestwesteu"}'
        action: Build an image
        dockerFile: '**/Dockerfile'
        imageName: '$(Build.Repository.Name):$(Build.BuildId)'

    - task: Docker@0
      displayName: 'Push image'
      inputs:
        azureSubscription: 'NR PMP DEVQA (21191caf-8a0a-4a0f-b34d-afae216ee5b3)'
        azureContainerRegistry: '{"loginServer":"acrmcataniatestwesteu.azurecr.io", "id" : "/subscriptions/21191caf-8a0a-4a0f-b34d-afae216ee5b3/resourceGroups/rg-mcatania-test-westeu/providers/Microsoft.ContainerRegistry/registries/acrmcataniatestwesteu"}'
        action: Push an image
        imageName: '$(Build.Repository.Name):$(Build.BuildId)'

    - bash: |
        find . -type f -name "manifest.yaml" -exec sed -i "s/#{ContainerRegistry}#/acrmcataniatestwesteu.azurecr.io/g; s/#{ImageTag}#/$(Build.BuildId)/g" {} \;
      workingDirectory: 'src/server'
      displayName: 'Update manifest with image version'
    
    - bash: |
        MONGO_URL=$(echo -n "mongodb+srv://matthewcatania:zFBTlJGEgXoKhH4S@cluster0.qdbd55u.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0" | base64)
        find . -type f -name "manifest.yaml" -exec sed -i "s/#{MongoConnString}#/$MONGO_URL/g" {} \;
      workingDirectory: 'src/server'
      displayName: 'Update manifest with MongoDB connection string'
    
    - task: KubernetesManifest@1
      displayName: 'Deploy latest image'
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'aks-mcatania-test'
        namespace: 'server-namespace'
        manifests: 'src/server/manifest.yaml'